### ISSUE TITLE
Podívat se na možnosti integrace chatovacích aplikací

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#1031]
Tohle je pokračování #957. Do vývoje vlastního chatu se nám logicky nechce ([nějaká diskuze tady ve Slacku](https://cesko-digital.slack.com/archives/CHG9NA23D/p1715777458295269)), takže se nabízí integrovat nějakou jinou chatovací aplikaci. Uživatelská představa je ta, že když budu chtít někoho v naší aplikaci kontaktovat, uvidím sadu tlačítek typu „Kontaktovat na Messengeru“, „Kontaktovat na Signalu“ a podobně. A v závěsu by to jistil náš Slack a přinejhorším vždycky e-mail.

V rámci tohohle ticketu se chceme podívat, jaké chatovací aplikace bychom mohli takhle integrovat a jak přesně by to vypadalo. Zajímají nás dva scénáře: 1) Jako koordinátor*ka projektu si chci dát do profilu v aplikaci odkaz na svůj XY chat, jak to udělám? Kde seženu příslušné URL nebo uživatelské jméno nebo ID? [Nejde nám jen o koordinátory, to je jen příklad.] 2) Když už tohle URL/uživatelské jméno/ID máme, jak to bude vypadat, když zájemce klikne na dotyčné tlačítko? Kam ho to hodí?

**Comment by anezkamll** [comment]
Telegram to má docela pěkné.
Adresa `https://t.me/username` otevře přímo chat s daným človekem, možno vyzkoušet u mě: https://t.me/anezkamll

**Comment by anezkamll** [comment]
WhatsApp to má pěkně popsané tu: https://faq.whatsapp.com/5913398998672934
Ozkoušeno na sobě, kdybych měla nainstalovanou app, tak mi to otevře chat v app, protože jsem to ale zkoušela v browseru, nechalo mě to otevřít odkaz ve webovém klientovi a fungovalo to ok.

**Comment by anezkamll** [comment]
Signlal už to umí taky, jen malinko složitěji/bezpečněji:
https://support.signal.org/hc/en-us/articles/6712070553754-Phone-Number-Privacy-and-Usernames
viz sekce Share username

**Comment by anezkamll** [comment]
Začínám v tom vidět nějaký pattern :grin: 
Facebook:
`https://m.me/username`, vyzkoušet možno na https://m.me/anezkamll, ale nezaručuju, že odpovím :grinning: 
V browseru mi to otevřelo okno s messengerem (který nepoužívám, takže to po mně chce přihlášení, ale předpokládám, že to bude fungovat), na mobilu jsem netestovala.

**Comment by zoul** [comment]
Slack: Existuje schéma `slack://`, kterým jde otevřít rovnou aplikace, URL do uživatelského profilu má schéma `slack://user?team={teamId}&id={userId}`, takže slack://user?team=TG21XF887&id=U01E2FZ1TA8 by měl být deep link do Slacku na profil Anež, kde je čudl Message (GitHub mně to nechce udělat klikací).

**Comment by anezkamll** [comment]
Skype též umí: https://softkeys.uk/blogs/blog/how-to-share-my-skype-contact-2

**Comment by anezkamll** [comment]
> Slack: Existuje schéma `slack://`, kterým jde otevřít rovnou aplikace, URL do uživatelského profilu má schéma `slack://user?team={teamId}&id={userId}`, takže slack://user?team=TG21XF887&id=U01E2FZ1TA8 by měl být deep link do Slacku na profil Anež, kde je čudl Message (GitHub mně to nechce udělat klikací).

Otestováno, funguje. :+1:

**Comment by anezkamll** [comment]
Viber s veřejným účtem: `https://viber.me/username/`
Viber s číslem by měl fungovat takhle: `viber://chat?number=%2B420-xxxxxxxxx` 
Viber už nepoužívám, takže neotestuju.
Vycházím z tohoto: https://stackoverflow.com/search?q=Create+a+link+that+will+open+Viber&s=e5f98d80-4875-41f8-b324-9d6e729e0932

**Comment by zoul** [comment]
Myslím, že v mladší cílovce bude hodně frčet chat na IG.

**Comment by anezkamll** [comment]
OK, pohledám. 

Jinak Discord to neumí, pokud nejsi s tím člověkem už propojený. Je k tomu docela dlouhé feature request vlákno, že by to lidi chtěli, ale... 
Můžeš mít link na svůj profil (toto je můj, přes Dev mode získáš svoje UserID, které doplníš do odkazu za `users/`) : https://discord.com/users/781246086647644210, ale pokud nejsme ještě na Discordu propojení, přesměruje tě to na tvůj vlastní profil.

**Comment by anezkamll** [comment]
Instagram sleduje klasický vzorec:
`https://ig.me/m/username`
Možno otestovat na https://ig.me/m/anyskamll 
Zprávy na IG používám výjimečně, vlastně jen ke komunikaci se svojí tatérkou nebo k rezervaci stolu v restauraci, kde nemají jiný komunikační kanál :grinning:. Ale já jsem už žena středního věku. :woman_shrugging: :smile:

**Comment by zoul** [comment]
Tohle je podle mě hotovo a zavírám, konkrétní implementace bude v #1052.
