### ISSUE TITLE
Přidat možnost filtrování a stránkování adresáře lidí

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#1053]
Pokračování #1042. Máme adresář lidí (`/people`), ale až v něm bude víc profilů, bude potřeba mít možnost ho filtrovat. Nejjednodušší možnost je obyčejné filtrování na klientovi, ale dá se to libovolně komplikovat, například filtrování podle dovedností a podobně. Bude potřeba domyslet.

**Comment by zoul** [comment]
Technické poznámky:

* Už to celé bude fungovat na klientovi. Asi by bylo dobré udělat pro nepřihlášené jen nějaký „teaser“ a veškerou funkcionalitu nechat pro přihlášené?
* Dávalo by smysl zavést nějakou privilegovanou roli, díky které by uživatel viděl i neveřejné profily? (Takový je reálný stav věcí, kdy placený tým chodí přímo do databáze.)
* Často se nám bude hodit na tuhle stránku odkázat s předvyplněným filtrem. Uděláme to tak, že se stav filtru bude automaticky promítat do URL? Hodilo by se to i pro sdílení dotazů.

**Comment by anezkamll** [comment]
Doplním: Tohle je za mě top priorita, abychom dodávali nějakou přidanou hodnotu jiným cílovkám, než dobrovolnictvu.
