### ISSUE TITLE
Přidat možnost nastavení profilovky

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#1055]
Doposud jsme podporovali pouze nastavení profilovky přes Slack, výhledově budeme chtít přidat možnost nastavení profilovky přímo – zejména protože do Slacku už nám lidi nepropadávají. Zvládnem uchovat ten Slack jako fallback?

PS. A případně bychom zároveň s tímhle mohli spláchnout nastavení jména?

**Comment by anezkamll** [comment]
@zoul nastavení jména už v profilu je, můžeme dodělat tohle? Opět mi na to dnes přišel požadavek :pray:

**Comment by zoul** [comment]
Určitě to můžem dodělat, je to jen otázka prioritizace. Můžeš na to myslet, prosím, a dostaneme se k tomu po prvním odbavení hashtagů? Rád bych ty hashtagy vzal prioritně, je v tom hodně kódu a změn v databázi, které se dlouho táhnou a rád bych je už měl za sebou. Případně by si tohle mohl vzít na starost Kuba, jak bude mít čas mimo #1094.

**Comment by anezkamll** [comment]
:eyes: @laurabaluchova zde ticket na fotky
