### ISSUE TITLE
Uživatelé chtějí lepší představu o tom, které změny nastavení se ukládají

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/app#1080]
Z testování vyplynulo, že v admin prostředí mají uživatelé zmatek, které změny se ukládají hned. U otevřených polí je tlačítko "Uložit", u checkboxů není, což je pro uživatele matoucí.
Možné řešení - nějaké vizuální potvrzené toho, že se změny zaznamenaly.

**Comment by drahoja9** [comment]
Vím, že to ještě nikde v appce není, ale co při každém uložení zobrazit "toast" (pardon, neznám český ekvivalent 😁) – https://apvarun.github.io/toastify-js. Přijde mi to celkem standardní a já jsem na to třeba celkem zvyklý.

A pak mě taky napadlo, jestli je vlastně potřeba mít ty ukládací tlačítka. Pokud se checkboxy (i našeptávač s lokalitami "Kde býváš k zastižení?") ukládají rovnou automaticky, určitě by to šlo zařídit i pro textová pole (buď po tom, co uživatel z pole "vyskočí" nebo když přestane na nějakou dobu psát).

**Comment by drahoja9** [comment]
V PRku #1092 jsem udělal nástřel, jak by to mohlo vypadat. Je to nasazeno [zde](https://app-b9zmefi1w-ceskodigital.vercel.app/).

Vzhledově můžeme samozřejmě upravit dle libosti. Co se týče funkcionality, notifikace momentálně nejde zavřít/zmizet ručně, ale to určitě lze také přidělat (teď se zavře po nějaké době sama [podle toho zda se jedná o chybu či úspěch](https://react-hot-toast.com/docs/toast#default-durations)).

V rámci toho jsem tedy odstranil i tlačítka "Uložit" v základních a kontaktních informacích, jak jsem psal výše, neboť k uložení dojde automaticky po vyjetí z políčka.

Jsem otevřený veškerým připomínkám, diskuzi i kritice. 🙂

**Comment by drahoja9** [comment]
Jakmile vyskočíš z políčka, tak se to uloží. Ale když se tam vrátíš zpět, funguje klasicky _CTRL+Z_. Nebo to samozřejmě můžeš zase smazat. 🙂
Ale chápu, že někdy je fajn mít tu explicitní možnost uložení. Mně se akorát nelíbí ta nekonzistence se zbytkem. Jestli by pak nebylo lepší mít jedno hromadné tlačítko "Uložit" pro celý formulář. Pak by to bylo konzistentní i s formulářem pro registraci nového uživatele.

**Comment by zoul** [comment]
Ctrl+Z funguje na počítači, ale na telefonu je to horší. I telefony mají Undo, iPhone dokonce rage-shake-to-undo :), ale myslím, že většina lidí ho nemá v aktivním repertoáru. Tlačítko pro celý formulář je blbé v tom, že je úplně dole mimo dohled – leda by nějak plavalo. Jako kompromis si dovedu představit ukládací tlačítko pro jednotlivé sekce, ale tím bychom zase zkomplikovali ten nejjednodušší případ přehození checkboxu – místo abych jen klikl na checkbox, musím kliknout a uložit. Domlouvali jsme se, že si ten toust ještě prohlídne Laura, tak uvidíme, s jakými dojmy přijde ona?

**Comment by drahoja9** [comment]
Jasné. Nemám na to nijak silný názor, jen se mi o chlup víc líbí varianta bez tlačítek. 
Předělám to ale samozřejmě tak, jak bude potřeba. ☺️
