### ISSUE TITLE
Sekce v profilu nejsou logicky řazené

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/app#1098]
Při natáčení onboarding videa jsem narazila na to, že část Soukromí nedává v současném řazení sekcé moc smysl. 
Je uprostřed profilu a po ní následují další osobnostní položky, což mi přišlo trochu nelogické, když jsem to procházela postupně.
Navrhovala bych dát to úplně nahoru nebo úplně dolů. Na začátek hned za registrační e-mail, nebo úplně jako poslední věc.

**Comment by anezkamll** [comment]
...můžu to zkusit předělat? :innocent: abych viděla, jestli jsem schopná porozumět kódu a nerozbít to :grin:

**Comment by zoul** [comment]
Jasně, určitě! Jediný zádrhel může být v tom, jestli jsou některé věci řešené jako větší „sekce“, kterou bys musela buď přesouvat jako celek, anebo rozbít na menší části, což pak může být náročnější. Ale sáhni do toho a uvidíš :)

**Comment by anezkamll** [comment]
Původně jsem chtěla hodit to soukromá hned pod přihlašovací e-mail, ale když jsem testovala jen prosté přehození bez rozdělení těch sekcí, abych viděla, jak to bude vypadat (a vyzkoušela, jestli to nerozbiju a jak to vůbec funguje), tak mi to vlastně dává smysl i takhle.

**Comment by zoul** [comment]
Vyřešeno v 9da57bc7b4ff8a2d6b3300c59e0a81bb0ba028ac.
