### ISSUE TITLE
Zjednodušený nábor lidí na role

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#1099]
Jeden z našich nejdůležitějších use casů je nabírání lidí na nějaké role. Nejčastěji to stále děláme přes ad-hoc formuláře v Airtable ([příklad](https://airtable.com/apppZX1QC3fl1RTBM/shrAuq9tVRMtiksIJ)), protože lepší variantu nemáme. Ta současná varianta ale trpí velkou řadou problémů – zejména se ptáme lidí pořád dokola na to stejné, vytváříme duplicity a zadaná data nám končí v nějaké random tabulce:

```
Databáze uživatelů:
    Jan Novák
        jan@novak.cz
        Typescript
        Praha
        …

Databáze projektu:
    Odpovědi z registračního formuláře:
        Jan Novák
        jan@novak.cz
        Typescript
        Praha
        …
```

Potřebujeme to změnit tak, aby přihlášený uživatel nemusel vyplňovat věci, které už o něm víme, a zároveň data z registračního formuláře zachovala nějakou vazbu na uživatelský profil:

```
Databáze uživatelů:
    Jan Novák   <---------------------------+
        jan@novak.cz                        |
        Typescript                          |
        Praha                               |
                                            |
Databáze projektu:                          |
    Odpovědi z registračního formuláře:     |
        Jan Novák --------------------------+
        (…dodatečné info z registračního formuláře…)
```

Technicky se to nabízí udělat tak, že odpověď na dotyčnou pozici bude vyžadovat přihlášení (případně registraci) a následně… nevíme co. Ty formuláře v Airtable jsou super flexibilní, tým s nimi umí dobře zacházet, ale nevím, jestli jde nějak zařídit ta vazba na stávající data. Airtable nabízí nějakou možnost [předvyplnit data přes URL](https://support.airtable.com/docs/prefilling-a-form-via-encoded-url), což je zajímavá cesta zhruba naším směrem – obávám se, že to nebude dost dobré, ale mrknu na to.

**Comment by zoul** [comment]
Rychlý technický test: Založil jsem tabulku [Test registrace](https://airtable.com/apppZX1QC3fl1RTBM/tblt6NRG5qaEieSkd/viw0pueXitKDaxJ8Y?blocks=hide) a udělal [odpovídající formulář](https://airtable.com/apppZX1QC3fl1RTBM/shr9G1eshf3CSNftZ). V tom formuláři je pole User, ve kterém jde vybrat z naší tabulky uživatelů – což samo o sobě není nic moc, ale jde použít [předvyplněné URL](https://airtable.com/apppZX1QC3fl1RTBM/shr9G1eshf3CSNftZ?prefill_User=recmU8tKzog4merHh&hide_User=true), kde toho uživatele vyplníme automaticky a zároveň to pole úplně schováme. Ve výsledku pak můžu do registrační tabulky přidat nový záznam, který se odkazuje na existující uživatelský profil a zároveň obsahuje dodatečné informace (potřebné například pro registraci na danou roli). Je to slibné, ale jsou tam dva háčky – jednak bezpečnost, jednak synchronizace do jiných databází. Ještě si s tím pohraju a napíšu.

**Comment by zoul** [comment]
Problém se synchronizovanými databázemi: Ty registrační formuláře se obvykle týkají projektů, a ty žijí v samostatných databázích (tedy nikoliv v databázi Users). A vazba z registračního formuláře na existující uživatelský profil nemůže vést napříč databázemi. Teď se často děje to, že databáze projektu (například App) má vlastní synchronizovanou tabulku uživatelských profilů. Takže bychom to chtěli udělat tak, aby byl registrační formulář vázaný na záznam z téhle synchronizované tabulky:

```
Databáze Users:
    User Profiles
Databáze App:
    User Profiles (synchronizovaná kopie z Users)
        Jan Novák <-----+
    Registration form:  |
        Jan Novák ------+
        (…dodatečné info z registračního formuláře)
```

Teď bychom tedy chtěli změnit stránku s vypsanou rolí v aplikaci tak, aby hlavní CTA _Mám zájem_ vedlo na nějaký takovýhle formulář a přidalo do URL databázové ID aktuálně přihlášeného uživatele. Tím by se to ID předvyplnilo do formuláře, vznikla by provazba na synchronizovanou kopii tabulky User Profiles a všecko by bylo krásné.

_Ovšem_ ta synchronizovaná kopie tabulky User Profiles _má odlišná databázová ID_ 💩 Takže zatímco v původní databázi User Profiles najdeme pod ID `recmU8tKzog4merHh` můj profil, v té synchronizované kopii žádný záznam s tímhle ID neexistuje. Aby to automaticky fungovalo, museli bychom na té stránce s rolí vědět, jaké je databázové ID přihlášeného uživatele _v databázi, kde žije registrační formulář_. Není to jaderná fyzika, ale je to pruda a nejspíš to bude vyžadovat vyplnění nějakých extra informací k dotyčné roli.

**Comment by anezkamll** [comment]
Přemýšlím, jestli se nedostáváme do situace, kdy by bylo jednodušší přemyslet celou architekturu těch databází tak, aby to co nejlépe sloužilo účelu sjednocování dat, než se snažit napasovat řešení na to stávající rozdělení. Co z toho má lepší poměr vloženého úsilí vs dlouhodobého gainu

**Comment by zoul** [comment]
Já jsem nad tímhle už trochu přemýšlel dřív a k ničemu kloudnému jsem nedošel. Ten model „každý projekt má vlastní databázi“ je v něčem velmi žádoucí, protože si pak lidi můžou hospodařit hodně nezávisle a nevznikají tím úzká hrdla. Na druhou stranu to „nezávislé hospodaření“ samozřejmě generuje ty nežádoucí divergence.

Proto mně tenhle drobný pragmatický posun ve stylu „nechte si svoje registrační formuláře a my vám je akorát zjednodušíme“ přijde docela dobrý. Z našeho pohledu (tedy celkového ekosystému) je za mě zásadní to, abychom už se _nikdy_ lidí znova neptali, jak se jmenujou nebo jaký je jejich mail.

**Comment by anezkamll** [comment]
Pročítám si to ještě zpětně a nepochopila jsem přesně, jak by fungovalo toto:
> jde použít [předvyplněné URL](https://airtable.com/apppZX1QC3fl1RTBM/shr9G1eshf3CSNftZ?prefill_User=recmU8tKzog4merHh&hide_User=true), kde toho uživatele vyplníme automaticky a zároveň to pole úplně schováme
Nechápu ten usecase, kdy by to mohlo být dobré, tedy jak se jako někdo, kdo se hlásí na nějakou roli, dostanu k tomu personalizovanému URL. Bylo by to v rámci toho, že jsem přihlášená v app? Že by se u každé role do přihlašování už rovnou propsal můj záklůadní profil?

**Comment by anezkamll** [comment]
Mám teď call s Marťou a Romčou, přinesu z toho nějaké vstupy, zároveň předám základní myšlenku z tohohle flow. 
A v každém případě základní myšlenku:

> za mě zásadní to, abychom už se nikdy lidí znova neptali, jak se jmenujou nebo jaký je jejich mail.

**Comment by zoul** [comment]
Je to myšlené přesně tak, jak píšeš – odpověď na roli by vyžadovala přihlášení do app. Takže když klikám na CTA „Mám zájem“, aplikace už by uměla předat do formuláře ID toho přihlášeného uživatele.

**Comment by anezkamll** [comment]
:information_source: teď ten reg form je v Users bázi, to by pro nás mělo být výrazně jednodušší celé

**Comment by zoul** [comment]
Pro pilot jo, ale výhledově nechceme, aby nám kvůli tomu všechny registrační tabulky naskákaly do Users. Zejména pokud tam potřebujou vazby na nějaké další projektové tabulky, které by tím pádem chtěli stěhovat do Users. My chceme ta projektová data z Users spíš vystrnadit než naopak :)

**Comment by anezkamll** [comment]
:hourglass: Zvládneme za měsíc nasadit tu verzi tak, aby to mohly holky použít na další běh ND?

Jak si to představuju v rámci vhodného flow a předschválily jsme si s Marťou a Romčou:
- člověk kouká na inzerát někde náhodně na LI
- proklikává se na web č.d k popisu role
- kliká na Mám zájem 
TADY SE CESTA VĚTVÍ
- pokud jsem registrovaná a přihlášená, objevuje se mi zjednodušený form pro roli
- pokud nejsem přihlášená, ale jsem registrovaná, objeví se mi možnosti přihlásit nebo registrovat, přihlásím se a objevuje se mi zjednodušený form pro roli
- pokud nejsem ani registrovaná, objeví se mi možnost se zaregistrovat, zaregistruju se, přihlásí mě to a objeví se mi zjednodušený from pro roli

Je to reálné?

**Comment by zoul** [comment]
Podle mě je to velmi reálné. V detailech se můžem někde šprajcnout, ale neposíláme raketu do vesmíru, určitě můžem dojít k něčemu zhruba v těchto intencích tak, aby to bylo lepší než současný stav.

**Comment by anezkamll** [comment]
OK, tak tomu dejme prioritu.

**Comment by anezkamll** [comment]
Doplňuju z dnešního syncu tři varianty reakce na roli nebo event, když jsem přihlášený:
Co se stane po kliknutí na tlačítko Mám zájem?
- rovnou se odešle reakce koordinátorovi, člověku, co reaguje, se jen ukázě notifikace ve stylu Víme o tobě
- ukáže se předvyplněný form, kde už se doplní jen věci relevantní k roli
- ukáže se úplně náhodný jakýkoliv form

**Comment by anezkamll** [comment]
Od Romči:
- líbí se mi, že se budou moci přihlásit po registraci, pro NNO by to mohl být overkills, pro dobrovolníky by to mělo být ok
- chápu správně, že mi pomůžete doklikat muj spešl formulář o další políčka, aby to bylo personalizované..?
- mám si vybrat jednou z těch 3 variant? co znamená, že se mi s tím bude hůř v airtable pracovat? bude to tedy v users nebo v databázi dle mého výběru (nezisk.digital?)
- hlavně tam nechci další admin, nechci psát nějakým interested lidem, ale potřebuji, aby se sami hlásili na calls či si přečetli budoucí vytuněnou webovku od Marti s medailonky, přišli na event... více automatických eventů vs. práce s jednotlivci
- chtěla bych, aby se mi moji zájemci překlápěli do NZ tabulky automaticky, tj. nechci do nějaké obecné tabulky něco vypisovat nebo si je ručně vybírat (jestli to je otázka?)
