### ISSUE TITLE
Toust scrolluje pryč

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#1107]
Stává se mně, že notifikační toust odscrolluje někam bokem. Repro: Otevřu uživatelský profil, sjedu někam níž, například na nastavení dovedností, udělám změnu, naskočí toust a prohlížeč mně sám vyjede nahoru. Děje se mně v Safari, jinde jsem nezkoušel. @drahoja9, nechtěl bys na to mrknout? Můžu případně dodat video nebo jinak pomoct. Nehoří. Díky!

**Comment by drahoja9** [comment]
Bohužel se mi nepodařilo nasimulovat ani v Safari (Version 18.0 (20619.1.26.31.6)):

https://github.com/user-attachments/assets/c5d124e9-0ec5-41ac-8fa0-9aa642e590be

Napadá mě nějaké rozšíření v prohlížeči, případně nějaké feature flags?

**Comment by zoul** [comment]
Aha, zajímavý! Zjistím, kde přesně se to děje – je dost možné, že je to glitch lokálního prostředí.

**Comment by zoul** [comment]
Už mně to nedělá 🤦‍♂️ Nějaký lokální glitch. Pardon za planý poplach! :)

**Comment by drahoja9** [comment]
Úplně v pohodě. 🙂
