### ISSUE TITLE
Jako uživatel chci rozeznat placené pozice od dobrovolnických

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#361]
Většina hledaných rolí je dobrovolnická, občas se tam ale vyskytne něco placeného. Jak ty role rozlišit? Zatím to děláme v titulku, což není moc systémové. Můžem prostě přidat „tag“ mezi ty, co se zobrazují pod popisem pozice?

**Comment by anezkamll** [comment]
Odbaveno přidáním tagů `dobrovolnická role` a `placená role`
