### ISSUE TITLE
Portál dobrovolníka - new features 

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/app#688]
ahoj @zoul, 
tady jen zkouším nahodit několik nových vlastností z pohledu silného recruitmentu (které jsme řešili v rámci Dobro on Board, ať se to nepoztrácí, když se neplánuje nějaký product design PD - **priorita je to nízká**, ale než se k tomu dostaneme, tak to zapomenu.
 
Jako dobrovolník, který se přihlásil na PD bych chtěla mít v rámci svého nastavení:   
- možnost zadat si preference výběru příležitostí 
- možnost aktivovat/deaktivovat "watchdog"/emailing na preferované příležitosti  (pokud nebude NL pro onboarding?)
- možnost aktivovat/deaktivovat si volbu "hledám zapojení" (s časovým omezením a možností popisu zapojení do čeho a na jakou dobu)
- dle hodnoty "hledám zapojení" - propsalo by se to do veřejného seznamu, ze kterého by bylo možné přímo oslovit do Slacku/ emailově takto označené dobrovolníky. 
- na pozadí by bylo fajn mít statistiku/sběr info. o příležitostech, na které se dobrovolník ozval 

FYI: @anezkamll  Anežko, můžeš pak prosím mrknout, jestli je to zhruba všechno? Díky (Romča nevím, jestli má GH účet vůbec?) 
díky g. 
(vím, že je to spíše do discussions, ale tam se mi nikdo z vás neozval, tak dávám rovnou sem :)

**Comment by anezkamll** [comment]
Dopíšu si sem jen nějaké poznámky:
- mapa dobrovolnéků -> v profilu si moct nastavit lokalitu, která by se exportovala na mapu? nebo to řešit ze Slacku, ale obecně, mapa dobrovolníků na PD
