### ISSUE TITLE
Double opt-in potvrzení při přihlášení k newsletteru skrze patičku na webu 

### ISSUE THREAD

**Issue by lukasnavesnik** [cesko-digital/app#743]
Momentálně leze do databáze spoustu "spamových" e-mailových adres. Chceme to zkusit ošetřit zapnutím double opt-in featury. V testovacím režimu. Budeme sledovat, kolik adres (a jaké) nedokončí přihlášení k odběru a jestli to jsou pro nás relevantní adresy.

**Comment by zoul** [comment]
[Dokumentace k API je tady](https://ecomailczv2.docs.apiary.io/#introduction/authorization), přijde mně z toho, že ten double opt-in tam jde selektivně _vypnout_, ale ne zapnout. Napsal jsem na uživatelskou podporu, abychom si to vyjasnili. Kdyby to fakt nešlo, můžeme zapnout double opt-in globálně pro celý seznam kontaktů a na potřebných místech ho takhle selektivně vypínat (například ve správě uživatelského profilu).

**Comment by zoul** [comment]
Už se ozvali z podpory, skutečně je potřeba zapnout double opt-in na celém seznamu kontaktů a následně ho vypínat při přístupu přes API tam, kde nám to dává smysl.

**Comment by zoul** [comment]
K tomuhle se teď vrátím, protože množství těch fejkových adres už zcela překračuje hranice. Nejspíš zkusím do formuláře přidat skrytý checkbox a budem doufat, že ho boti vyplní ([nápad odsud](https://stackoverflow.com/a/15320112/17279)).

**Comment by zoul** [comment]
Implementováno. Zavřu a budu sledovat, pokud spam neustane, otevřem znova.
