### ISSUE TITLE
Veřejný profil člena komunity na webu Česko.Digital

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/app#854]
Překopírovávám nápad od Petra Illka, viz [Slack](https://cesko-digital.slack.com/archives/CHG9NA23D/p1687289829431369).

> **Veřejné (volitelně) profily na webu**
> Současné profily na webu jsou neveřejné. Profil tady na Slacku je vlastně taky neveřejný (jen pro komunitu).
> Líbilo by se mi, kdyby existovala adresa jako `cesko.digital/komunita/petr-illek`, na kterou bych veřejně mohl odkázat. Mohli by tam být nějaké informace o projektech do kterých jsem se zapojil (tohle info už máme), informace z mapy (tohle taky máme), odkazy ze slack profilu (to taky máme). Navíc tam přidat třeba nějaký textový prostor pro vlastní vyjádření. Dá se to dál gamefikovat třeba pomocí různých badge – Slack Master 05/2023, X-let v komunitě, ambasador atp.
> Jako příklad dávám můj profil na [drupal.org](https://www.drupal.org/u/petr-illek), kde třeba je i drobná chyba v tom řádku On [Drupal.org](http://drupal.org/) for … kde se pár dní v roce objevuje 9 let a 12 měsíců, místo 10 let – a lidi těch pár dní vyhlížejí a dělají si screenshoty a ve výsledku je to taky typ propagace.
> 

Můj komentář:
Mně to přijde jako fajn nápad do portfolia toho, jak dát kredit dobrovolníkům za to, že v Česko.Digital pomáhají. Nenutit to, ale dát to jako možnost - v rámci profilu na PD mít zaškrtávátko, které by umožňovalo dát část info na profoilu jako veřejné. Napojení na informace z tabulky Teams, které by prolinkovalo projekty, na kterých byl člověk zapojený, případně skills, pokud by chtěli. Určitě podle mě stojí za zvážení.

**Comment by zoul** [comment]
Tohle určitě chceme a dlouhodobě k tomu směřujeme. Technicky to není nijak zvlášť složité, ale je tu velký objem „produktové práce“, kterou je potřeba udělat, než se to bude programovat. Například: bude mít profil každý člen komunity, nebo to bude opt-in? Které informace budou na profilu vidět? Budou si uživatelé moct vybrat, co chtějí mít na profilu veřejně? Etc. Proto bychom teď radši ještě počkali, je tu významný souběh s projektem „redesignu komunity“ s Q Designers. Kde, pro představu, jeden z konceptů pro testování (WIP!) vypadá takto:

![platforma](https://github.com/cesko-digital/web/assets/95329/ee45c892-a32a-4d2a-9a16-7bf3084a39b8)

**Comment by zoul** [comment]
K tomuhle jsme se teď konečně dostali, ale pro přehlednost jsem založil nový ticket, takže tenhle zavírám ve prospěch #1042.
