### ISSUE TITLE
Chatovací tool v aplikaci

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/app#957]
Přesný popis nechám na @zoul, ale z produktového pohledu, oč nám jde:
- chceme možnost vyměňovat si s lidmi zprávy předtím, než se připojí do projektu
- chceme dát možnost poslat zprávu někomu z kmenového týmu bez nutnosti registrovat se do Slacku
- chceme minimalizovat potřebu vyskakovat ven do e-mailu

Proč to chceme:
- připojení do projektu není přímočaré, potřebujeme s lidmi mluvit, než se dohodneme, že se do projektu připojí, nestačí jen Ping talčítko
- nechceme odvádět lidi z platformy pryč nebo je nutit rovnou chodit do Slacku, když celý point platformy byl nenutit lidi chodit do Slacku, protože velká část obsahu se bude dít na platformě a nemusí propadnout králičí norou

Varianta:
- integrovat možnosti Discourse

**Comment by zoul** [comment]
Tohle byl nějaký úvodní impulz, ze kterého jsme vyšli, ale pochopitelně to není „zralý feature request“, spíš námět k debatě o dalším směřování a nástrojích.

Implementaci vlastního plnohodnotného chatu se chceme pokud možno vyhnout, protože by to byla hromada práce a tříštili bychom komunikaci do dalšího nástroje. Na druhou stranu to vypadá, že pro velkou část výměn je ten chat potřeba – například když se někdo chce zapojit do projektu, nevystačíme si prostě s čudlíkem „Chcu se přidat“, který by jen z druhé strany potvrdila koordinátorka projektu. Skok do Slacku je relativně náročný, komunikace mailem blbá. Dávalo by smysl nějak „integrovat“, například přes API, Discourse nebo Slack? Z pohledu UX je tu dobrá paralela s běžným chatem na webu e-shopů a jiných webů.

Popřemýšlíme a vrátíme se k tomu.

**Comment by zoul** [comment]
Ještě jsem narazil na [Chatlio](https://chatlio.com). Miluju jejich motto: _You don't need another chat client_ :) Takhle to funguje:

>When you setup Chatlio, you pick one of your channels in Slack where you want new messages from your visitors to show. Next you add the Chatlio javascript embed code to the pages on your site where you want the chat widget to show. When somebody chats at you, their first message will be delivered to the “chatlio” channel in Slack. Anyone on your Slack team that is a member of the Chatlio channel can pick up the visitor by clicking on a link taking the conversation to a dedicated Slack channel. Chatting to a visitor is very much like any other Slack conversation: links, emojis, images, code snippets and uploaded files work just the same.

Bohužel je to spíš ta varianta „uživatelská podpora“, tj. jako uživatel zvenčí píšu nějaké anonymní tlupě lidí, ze které se mi někdo ozve. Zatímco by bychom chtěli, aby bylo možné napsat rovnou konkrétnímu člověku, například koordinátorce.

**Comment by anezkamll** [comment]
Zatím mně přijde nejlepší varianta s těmi odkazy na existující služby, moje zkoumání ukazuje, že jsou na to ty aplikace (alespoň ty defaultně chatovací) zařízené, že sdílíš přímo odkaz na chat s tebou.

**Comment by zoul** [comment]
Momentálně se všichni shodujeme, že proklik do jiné aplikace (chat, mail) je ideál, takže tohle zavírám ve prospěch #1031. Jestli jsme se někde špatně pochopili, reklamujte, díky!
