### ISSUE TITLE
Navigační lišta 0. úrovně napříč weby

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/app#976]
Problém:
Není jasné, že appka, blog, fórum a web jsou z jednoho ekosystému.
A není jasné, že se mezi nimi dá nějak jednoduše pohybovat.

Řešení:
Nadřazená navigační lišta.

![20240209_094536](https://github.com/cesko-digital/web/assets/6068291/ea86b885-dd23-4efa-ad69-c14d97efdc2d)

**Comment by anezkamll** [comment]
Tohle za mě dostává větší a větší prioritu @zoul 
Dostaneš se do ní z webu, ale na web zpět už nevede cesta a to vnímám jako velký problém.

**Comment by anezkamll** [comment]
Chceme sjednotit navigaci napříč našimi prostory:
Web, App (pracvoní název), Blog, Fórum
Mělo by se mezi nimi dát volně přecházet, aby bylo jasné, že vše jsou jen různé prostory spadající pod jeden ekosystém.
Nějak takhle:
![WhatsApp Image 2024-04-10 at 18 15 04](https://github.com/cesko-digital/app/assets/6068291/c23ee9d4-dc33-44e1-95a1-2b11c984c984)
V horní části obrázku je nakreslená navigace s drop-down menu pod jednotlivými hlavními "kategoriemi". Ve spodní části pak nějaké pořadí v jednotlivých částech.

Kde jsme schopní to nejjednodušeji upravit:
- web (naklikat ve Webflow)
- app (nakódovat)
- blog (nakódovat)
To bychom dělali prioritně.
Diskutuj.Digital bude potřeba víc promyslet, abychom to dostali také do horní lišty (např. https://forum.workflow.ooo/ to má až "v tělě" fóra, to taky není blbý, ale my bychom to ideálně měli podobně napříč všemi platformami). 

Co nyní potřebujeme:
- [ ] navrhnout design
- [ ] navrhnout technické řešení pro Diskutuj.Digital
- [ ] naklikat Webflow
- [ ] naprogramovat blog
- [ ] naprogramovat app
- [ ] upravit Diskutuj.Digital

**Comment by anezkamll** [comment]
Jo a taky potřebujeme vymyslet finálně, jak budeme říkat app.cesko.digital :grin:

**Comment by anezkamll** [comment]
@laurabaluchova mrkla by ses případně na ten design?

**Comment by laurabaluchova** [comment]
Na navrhu uz pracujem, pytala som i editorske prava do Figmy, email mi dosiel ze ich mam ale Figma to zatial nevie a stale pise request sent... Ked to pojde hodim to tam, zatial posielam prvy draft na desktop :) tablet a mobil budu zaujimave tam to bude musiet byt nejake zanorene do seba..
<img width="407" alt="navigace_desktop" src="https://github.com/cesko-digital/app/assets/106871634/3cd6e511-cf3a-47e5-9719-658e654f371d">

**Comment by laurabaluchova** [comment]
pozrite prosim na ten [desktop vo Figme](https://www.figma.com/file/ignBylJ9FbJxhI8jbfMAtv/%3EC.D-%2F-Web-(update)?type=design&node-id=5774%3A51906&mode=design&t=KP5zrZmNpLQQfNjN-1)

Buduci tyden by som mrkla na tablet a mobil, tam ako som pisala to bude zanorenejsie, ked vas k tomu napadne vopred nejaka pripomienka dajte prosim vediet.. :)

**Comment by anezkamll** [comment]
Hm no já se do té Figmy z nějakého důvodu nedostanu... @zoul ty jo?

**Comment by zoul** [comment]
Já jo!
