### ISSUE TITLE
Přechod na identitu v aplikaci

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#979]
Navazujeme na brainstorming #956, rozpracovali jsme přechod na „identitu Česko.Digital“ [v Miru](https://miro.com/app/board/uXjVPxeYSuk=/). Vyplývají z toho následující fáze:

* [x] #980
* [x] #981
* [x] #982
* [ ] #983
* [ ] #984

První tři kroky jsou nutné a je potřeba je implementovat v tomto pořadí a ideálně co nejrychleji po sobě. Přihlašování a registrace pomocí účtů třetích stran jsou už volitelné kroky. Podrobnosti popíšu v jednotlivých ticketech, tady nechám celkový kontext.

Co chceme:

* Zbavit se složitého registračního UX Slacku, které nemáme pod kontrolou
* Zjednodušit přihlašování k aplikaci (OAuth flow Slacku je pro některé uživatele matoucí)
* Získat možnost používat tuhle „identitu č.d“ pro další služby (například Diskutuj.Digital)

Co nechceme:

* Zbavit se Slacku. Budeme ho používat dál, ale nebudeme ho lidem cpát jako výchozí nástroj pro interakci s č.d

**Comment by martinwenisch** [comment]
Planujes pouzit NextAuth? Dokazu s tim pomoct (dobrou radou). Vyplati se to (oproti jinym resenim v Nextu, nebo custom OAuth reseni).

**Comment by zoul** [comment]
Rozhodně NextAuth.js, „custom OAuth řešení” je leda tak dobrý nápis na náhrobní kámen :) Zkusím do toho naběhnout a kdybych se někde šprajcnul, ozvu se, díky moc!

**Comment by zoul** [comment]
Tohle beru jako hotové, přihlašování externími službami můžem dořešit později.
